services:
  - type: web
    name: fake-news-detector
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    build:
      - npm install
